### PR TITLE
phpunit on require-dev

### PR DESCRIPTION
**Pull request by harikt**

### CODE REVIEW

**Comment by harikt** [comment]
Moving discussion from the commit to here

> The reason it's not is that it's required by opulence/framework for the console and HTTP integration test suite.

If https://github.com/opulencephp/Opulence/blob/eb3ad51633d4f13a24699c56754f6d29c48efa26/composer.json#L70 is there then the `require` stuffs will be all installed. That means `phpunit` is installed. When you are doing testing then people will definitely install phpunit. So that require should be moved according to my opinion.

Thanks!

**Comment by opulencephp** [comment]
I should clarify - it's not the unit tests for the framework I'm talking about.  Opulence provides a [console integration test class](https://github.com/opulencephp/Opulence/blob/1.0/src/Opulence/Framework/Console/Testing/PhpUnit/IntegrationTestCase.php) and [HTTP integration test class](https://github.com/opulencephp/Opulence/blob/1.0/src/Opulence/Framework/Http/Testing/PhpUnit/IntegrationTestCase.php) to integration test applications that use Opulence.  These both extend the `PHPUnit\Framework\TestCase`.  If I don't require `phpunit`, then these classes will not work.

**Comment by harikt** [comment]
@opulencephp so the question when do you do integration test ? Do you think on production ?

If you think it is dev, then you should move `phpunit` to `require-dev` . If user wants they will install on dev the dependencies and do testing.

phpunit should not be kept in require and if you do so then there is huge load on autoloading when you do `composer dumpautoload -o`

**Comment by OddGreg** [comment]
@opulencephp 

It's true that the integration classes will not work without `PHPUnit` installed. However, I agree that it should be moved to `require-dev` so it can be disabled in production. 

Out of curiosity - does your `Composer` class, during start-up, do anything that requires that `PHPUnit` is available in all cases? I haven't quite finished analyzing the breadth of how it is use.

**Comment by opulencephp** [comment]
@harikt I've thought about it, and I've decided you're right.  I will merge the PR when I get home.

@OddGreg As far as I'm aware, the `Composer` class does not require `PHPUnit` at all.

**Comment by OddGreg** [comment]
@opulencephp 

Excellent!

**Comment by harikt** [comment]
:-) . Thank you.

**Comment by opulencephp** [comment]
Thanks for contributing!  And thanks for sticking around with Opulence for so long!

**Pull request merged**
