### PR TITLE
Get Matched Route in Middleware

### LINKED ISSUE #70: Get Matched Route in Middleware
Since middleware is called from `Opulence\Framework\Http\Kernel::handle()` before routing takes place, I don't believe there's an elegant way to obtain the matched route in middleware.

I propose that a new method `Opulence\Routing\Router::match()` be created and that `Opulence\Routing\Router::route()` be refactored to make use of `Opulence\Routing\Router::match()`.

As a practical example, one would be able to obtain the controller name through middleware using the following:

```php
class MyMiddleware implements IMiddleware
{
    private $router;

    public function __construct(Router $router)
    {
        $this->router = $router;
    }

    public function handle(Request $request, Closure $next) : Response
    {
        $controller = $this->router->match($request)->getControllerName();

        /* Do something with $controller... */

        return $next($request);
    }
}
```

### PR DESCRIPTION
**Pull request by rdnn**
Fix #70

### CODE REVIEW

**Comment by opulencephp** [comment]
Thanks for the PR!  I agree - this feature is necessary.  Two things:

1. This will not be very performant for large numbers of routes.  I'd suggest adding a matched route cache to the router so that we're note double-matching routes in the router and middleware that needs the matched route.
2. With the above feature, could you add some unit tests to cover `match()`?

Thanks again!

**Comment by rdnn** [comment]
@opulencephp Sorry; completely slipped my mind! I included some unit tests for `match()`.

Also, I implemented some caching into `match()`. However, since there's no persistence across requests, there's still going to be a performance penalty as we now have the overhead of setting up the cache array each request. Although, from my rudimentary testing, it doesn't seem like the overhead is much and doesn't impact performance in any appreciable way.

**Comment by alchimik** [comment]
I think it is better to add the cache separately, in another pull request.
I doubt that this cache implementation is correct, but can't check now.

**Comment by rdnn** [comment]
@alchimik You're not incorrect. Without some sort of persistence (redis, memcache, etc.) the caching solution in the PR works for everyone using `match()` in middleware, but does nothing for those who aren't (in fact, it introduces _some_ performance degradation, even if not appreciable).

**Comment by alchimik** [comment]
```php
    public function testCache()
    {
        $controller = NonOpulenceController::class . '@index';
        $this->router->get('/foo/:id', $controller, ['host' => 'host1']);
        $this->router->get('/foo/:id', $controller, ['host' => 'host2']);

        $server = [
            'REQUEST_METHOD' => RequestMethods::GET,
            'REQUEST_URI' => '/foo/123',
            'HTTP_HOST' => 'host1'
        ];
        $request1 = new Request([], [], [], $server, [], []);
        $server['HTTP_HOST'] = 'host2';
        $request2 = new Request([], [], [], $server, [], []);
        $server['HTTP_HOST'] = 'host3';
        $request3 = new Request([], [], [], $server, [], []);

        $this->router->route($request1);
        $this->assertEquals('host1', $this->router->getMatchedRoute()->getRawHost());

        $this->router->route($request2);
        $this->assertEquals('host2', $this->router->getMatchedRoute()->getRawHost());

        $this->expectException(HttpException::class);
        $this->router->route($request3);
    }
```
failed with cache, because cache does not check host and scheme

**Comment by rdnn** [comment]
@alchimik This is only true if we're writing to persistent storage or if someone is manually creating a request in the framework. Since the former isn't true right now, the latter is the only reason the test would fail in production.

The cache would have to take into account `rawHost`, `pathVars`, `methods`, `isSecure`... maybe others that I'm missing.

**Comment by rdnn** [comment]
After further thought, there are too many issues to make this workable right now. An entire route caching life cycle needs to be defined and implemented before implementing the `match()` method.

**Pull request closed without merging**
