### PR TITLE
composer: make PHP version future-proof

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by meinemitternacht** [comment]
Pretty sure this won't pass with PHP 7.1

**Comment by opulencephp** [comment]
@meinemitternacht If I understand Composer version constraints correctly, `^7.0` means `>=7.0.0,<8.0.0`.  I'm not sure @TomasVotruba's change will prevent Opulence from working with PHP 7.1.  Or, have I missed something?

**Comment by meinemitternacht** [comment]
Disregard, I should not have assumed similarity between their syntax and Regex.

**Comment by TomasVotruba** [comment]
@opulencephp That is exactly right. `^7.0` allow all 7.x versions, but not above.
Thus, 7.1 will work.

**Comment by f3l1x** [comment]
@TomasVotruba 

`~7.0` and `^7.0` are equal right?

-----

By official documentation.

> ~1.2 is equivalent to >=1.2 <2.0.0
> ^1.2.3 is equivalent to >=1.2.3 <2.0.0

Am I right?

-----

PS: I have always thought that caret (`^`) has the main purpose for for 3 digits, I mean patch version. 
Like for example `^7.0.8`. It means I want to obtain higher then 7.0.8 and lower then 8.0.0. 

Thanks for explanation.

**Comment by opulencephp** [comment]
They are not equal:  http://stackoverflow.com/questions/22343224/difference-between-tilde-and-caret-in-package-json

**Comment by TomasVotruba** [comment]
@f3l1x For php version check they are the same.

**Comment by TomasVotruba** [comment]
Thank you @opulencephph!

**Pull request merged**
